INHERIT: active-handout.yml

site_name: Linux Basico

extra:
  custom_variables:
    repo_aps: https://github.com/rbcuenca/LinuxBasico
    repo_aps_git: https://github.com/rbcuenca/LinuxBasico.git

extra_javascript:
  - js/tabs.js
  - js/termynal.js
  - js/custom.js

extra_css:
    - css/termynal.css

nav:
  - 'Home': index.md
  - "Dia 1":
    - "01 - VirtualBox": modules/01-virtualbox/VirtualBox.md
    - '02 - Dual Boot': modules/02-dualboot/Dualboot.md
    - '03 - Instalando o Ubuntu': modules/03-ubuntu/Ubuntu.md
    - '04 - Atualização do Sistema': modules/04-atualização/Atualizacao.md
  - "Dia 2":
    - "04 - bla": modules/04-bla/bla.md
    # - "03 - Batch prediction":
    #   - "Part 1":
    #     - modules/03-batch/intro.md
    #   - "Part 2":
    #     - modules/03-batch/sql.md
    #     - modules/03-batch/db_tool.md
